 
const OK=200
const CREATED=201


const BAD_REQUEST=400
const UNAUTHARZED=401
const FORBBIDEN=403
const NOT_FOUND=404
const METHOD_NOT_ALLOWED=405
const DOBLICATED_RESOURSEC=409

const INTERNAL_SERVER_ERROR=500

export default {
    OK,
    CREATED,
    BAD_REQUEST,
    UNAUTHARZED,
    FORBBIDEN,
    NOT_FOUND,
    METHOD_NOT_ALLOWED,
    DOBLICATED_RESOURSEC,
    INTERNAL_SERVER_ERROR
    
}